name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn
      
      - name: Decode OpenVPN config
        run: echo "${{ secrets.OPENVPN_CONFIG }}" | base64 -d > vpn-config.ovpn
      
      - name: Create authentication file
        run: |
          echo "${{ secrets.VPN_USERNAME }}" > auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> auth.txt
          chmod 600 auth.txt
  
      - name: Update OpenVPN config to use auth file
        run: echo "auth-user-pass auth.txt" >> vpn-config.ovpn
  
      - name: Start OpenVPN
        run: sudo openvpn --config vpn-config.ovpn  --daemon --verb 3

  
      - name: Verificar conexión VPN (IP pública)
        run: curl ifconfig.me # Verifica si la IP cambia al conectarse a la VPN
      
      - name: Ping an IP address
        run: ping -c 4 10.0.0.4 || echo "Ping failed, continuing..." # Verifica conectividad a través de la VPN

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Your task behind VPN
        run: |
          echo "Running tasks behind VPN..."
        
      - name: Verificar logs de OpenVPN
        run: sudo cat /var/log/syslog | grep openvpn
      
      - name: Stop OpenVPN
        if: always()
        run: sudo killall openvpn
