# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn
      
      - name: Decode OpenVPN config
        run: echo "${{ secrets.OPENVPN_CONFIG }}" | base64 -d > vpn-config.ovpn
      
      - name: Create authentication file
        run: |
          echo "${{ secrets.VPN_USERNAME }}" > auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> auth.txt
  
      - name: Update OpenVPN config to use auth file
        run: echo "auth-user-pass auth.txt" >> vpn-config.ovpn
  
      - name: Start OpenVPN
        run: sudo openvpn --config vpn-config.ovpn --daemon
  
      - name: Verify VPN connection
        run: curl ifconfig.me # Esto debería mostrar la IP del servidor VPN
      
      - name: Ping an IP address
        run: ping -c 4 10.0.0.4
  
      - name: Your task behind VPN
        run: |
          # Aquí ejecutas los comandos que quieres que se realicen a través de la VPN
          echo "Running tasks behind VPN..."
        
      - name: Stop OpenVPN
        run: sudo killall openvpn